### ISSUE TITLE
[Toolkit] Add configuration options to LeafletView

### ISSUE THREAD

**Issue by sensiasoft** [opensensorhub/osh-js#1]
The LeafletView constructor should take options to configure the layers and initial view. This could be an object like:

new OSH.UI.LeafletView("main-container", {
   baseLayer: {},
   overlayLayers: [],
   initialView: {lat: 34, lon: -86, zoom: 15},
   autoZoomOnFirstMarker: true   
});

And maybe more options down the road...

**Comment by mdhsl** [comment]
Added:

- baseLayers
- overlayLayers
- defaultLayer
- initialView
- autoZoomOnFirstMarker

[Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/1/)
