### ISSUE TITLE
PTZ Camera icon needs recentered

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-js#109]
Related to #108 

The icon (icon: "./models/PTZwithConeSmooth.glb") used for the PTZ camera in the GeoHSV demos is not centered properly; it does apparently rotate properly but does not coincide with the green bracket.

![screen shot 2018-03-05 at 4 15 59 pm](https://user-images.githubusercontent.com/7469574/37005428-a1b9e188-2099-11e8-9a60-a4bf627a3c0b.jpg)

**Comment by alexrobin** [comment]
This is specific to the GeoHsv application although we can probably improve how icon and model anchor coordinates are handled in the toolkit.
