### ISSUE TITLE
Loosing window focus affects real-time display

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-js#123]
When focus is removed from browser window (occluded/hidden by other window) data stream continues to receive data.  However, when focus is granted back to browser window the display seems to play buffered data seemingly as fast forwarding until it catches up to real-time.

**Comment by mdhsl** [comment]
> When focus is removed from browser window (occluded/hidden by other window) data stream continues to receive data. However, when focus is granted back to browser window the display seems to play buffered data seemingly as fast forwarding until it catches up to real-time.

You can test a new version of FFmpeg.js and FFmpegViewer into this PR: https://github.com/opensensorhub/osh-js/pull/124

Tell me if this fixes the problem
