### ISSUE TITLE
CesiumView does not update Color or Label when styler updated

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-js#130]
For Markers (PointMarkers) on CesiumView, if styler color or label are updated, label is not updated correspondingly with regards to Cesium object and visualization.

**Comment by alexrobin** [comment]
Confirmed, this needs to be added in the updateMarker method of CesiumView:
https://github.com/opensensorhub/osh-js/blob/master/Toolkit/src/osh/ui/view/map/osh-UI-CesiumView.js#L407
