### ISSUE TITLE
Cannot unregister view from EventManager

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-js#132]
Even after a view object is removed (no more reference to it), the callback(s) registered with `EventManager` remain, which can cause performance drag and other issues.

We need a `remove()` method on `EventManager` and `EventMap` and keep a handle to the callback in the views so we can remove them later when the view is destroyed.

We could also provide a separate method to register/unregister a view to the event bus so that visualization can be easily paused/resumed.

**Comment by mdhsl** [comment]
Done in ES6 branch
