### ISSUE TITLE
Image Draping broken

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#187]
The Image Draping is not working anymore, neither on the react or vuesjs demos. The draping is not synchronized with the map

![image](https://user-images.githubusercontent.com/6577027/87432120-dd59f980-c5e7-11ea-94e6-c95f88753c18.png)

**Comment by mdhsl** [comment]
It is not a bug. It is happening because the CPU is not fast enough to decode the h264 frame as fast as it needed to synchronize with orientation and position. It is falling behind.  That kind of use case should use the new next data synchronizer algorithm to be sure the data are synchronized together between sensor in a same entity

**Comment by mikebotts** [comment]
Hi Matt. Should this issue NOT be closed but maybe just redefined as something that needs to be further looked at in the future. Its still shown not to be working even if it's not a bug, right?


Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com <http://www.botts-inc.com/>
https://opensensorhub.org <https://opensensorhub.org/>
256-652-0165

**Comment by mdhsl** [comment]
Well we can re-open the issue but I am not sure about the solution for this

**Comment by alexrobin** [comment]
I would just modify the demo to use the Data Synchronizer.

**Comment by mdhsl** [comment]
It will not fix the problem. The problem is the too much data are going to be decoded by the view and take some lag because the CPU cannot decode as fast as it should. So we get a lag

**Comment by alexrobin** [comment]
Yeah you're right.
Why is decoding taking such a long time in this case?

**Comment by mdhsl** [comment]
I think the resolution + the framerate are too much for my laptop. On my desktop, I don't reproduce the problem. You can reproduce this using the chrome dev tool which allows to slow down the CPU to 25% for example.

A solution would skip frame into the FFMpegView when we are too far from the current time but it is simple to implement

**Comment by alexrobin** [comment]
It's strange because it used to be running fine on my laptop.
I haven't tested the latest version though.

**Comment by mdhsl** [comment]
Try to use the CPU throttle using chrome: dev tool -> performance tab -> CPU throttling

You should reproduce the problem

**Comment by mdhsl** [comment]
Tested on last release and it seems working fine even using CPU throttling 6x. I think we can close this issue
