### ISSUE TITLE
Building toolkit broken?

### ISSUE THREAD

**Issue by richard3d** [opensensorhub/osh-js#20]
Hello,

I tried running make.sh which I assumed built the minified library and put in the 'dist' folder, however I get an error right now where it is looking for directories that do not seem to exist in the project. Example output: 'ERROR - Cannot read: src/osh/datasource/osh-DataSource-video.js' Is this the correct approach to 'building' the library?

**Comment by mdhsl** [comment]
Hi,

You are right, the make.sh is deprecated and broken. For now, you can use the while directory and import what you need to build what you want. 

You can find some examples here:

[LeafLet example](http://opensensorhub.github.io/osh-js/Toolkit/tests/1/)

[Chart example](http://opensensorhub.github.io/osh-js/Toolkit/tests/3/)

[Video example](http://opensensorhub.github.io/osh-js/Toolkit/tests/6/)

Some stuff are missing such as tutorials, comments, documentation, make.sh etc.. It's included in the roadmap.
