### ISSUE TITLE
[Toolkit] Add methods and actions to reconnect data sources

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-js#22]
It would be useful to be able to reconnect data sources without reloading the page.

It could be done via methods on the DataProviderController to reconnect a single DataSource, all DataSources attached to an Entity, or all DataSources registered with the controller

**Comment by mdhsl** [comment]
Added support to disconnect/reconnect a dataSource based on event handling. The dataProvider listen for DISCONNECT/CONNECT event and for each event received, will forward the right action to the concerned dataSource. The event content contains a list of dataSources, thus in one event we can disconnect/reconnect a set of dataSources.

To illustrate this functionnality, a new button has been added to the DialogView and allow to disconnect/reconnect DS.
