### ISSUE TITLE
Lock aspect ratio on video and image frames

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-js#23]
By default, set a lock on video and image frames to preserve the x-y aspect ration on frame resizing so images and video don't get distorted. Should probably be an boolean option that can be set in configuration though.

**Comment by sensiasoft** [comment]
I found a way to fix the aspect ratio of the video canvas, but it doesn't enforce the aspect ratio of the entire dialog wrapping the canvas. I'm using for now since it's better than nothing. The CSS trick is to use  "height: calc(100%-0px)" instead of just "height: 100%"

**Comment by mdhsl** [comment]
We can now use the keepRatio property provided by the dialog
