### ISSUE TITLE
[Showcase / Synchronization] Multiple videos synchronized lag

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#284]
If we run the 'Display multiple videos using forward/pause/play/backward control using the same DataSynchronizer', and if we click on the forward button, it will see the data coming back and forth. It seems to be an error in data synchronization reset.

**Comment by alexrobin** [comment]
Link to video showing the problem:
https://drive.google.com/file/d/1IGJ7h6t4uJ_dK7IsPR5PvYUDqyz1cUTi/view?usp=sharing
