### ISSUE TITLE
Use DataSource objet  instead of DataLayer

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#342]
Use a DataSource object as shortcut instead of DataLayer into the Video Views

**Comment by alexrobin** [comment]
Shouldn't we use a dataSourceId property instead of a full DataSource object?

**Comment by mdhsl** [comment]
Using a dataSource would provide more information such as whether or not it belongs to a dataSynchronizer (useful for example in the case of the RangeSlider) or others

**Comment by alexrobin** [comment]
For views like VideoView, it should be just dataSourceId so views stay properly decoupled from the DataSource.

The case of RangeSlider is different because it's also a controller, so in that case, yes, we need to pass in the DataSource or DataSynchronizer object directly.
