### ISSUE TITLE
Rename packages

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-js#348]
Let's rename some packages before building an NPM dist version:

`osh` -> `core`
`osh-ext` -> `ext`
`osh-vue` -> `vue`
`dataconnector` -> `protocol`
`datareceiver` -> `datasource`
`datasender` -> `datapush`
`datasynchronizer` -> `timesync`

Also merge `event` and `events` package into `event`

**Comment by mdhsl** [comment]
Some questions here:

* Do we have to refactor DataConnector class into Connector as well?
* DataSynchronizer class into TimeSync?
* package osh -> core?
* package osh-ext -> ext ?
* package osh-vue -> vue ?

**Comment by alexrobin** [comment]
No, don't rename the `DataConnector` and `DataSynchronizer` classes, just the packages.
And ok to rename the top level packages as you suggest:
- osh -> core
- osh-ext -> ext
- osh-vue -> vue

**Comment by mdhsl** [comment]
Like for example OpenLayers, we have to do something like:

**Comment by mdhsl** [comment]
done 29b8ebd6efef4054c73c42b9f70086d6141c779c
