### ISSUE TITLE
Need License/Headers on all Code

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-js#37]
We need to put the appropriate license and headers on all OSH js files, plus we need authors for specific classes.

Besides of course being good practice, we need this to move through ATO and we will need it to join LocationTech.

**Comment by mdhsl** [comment]
Added license + authors as header of all Js files

**Comment by mikebotts** [comment]
Thanks Mathieu. Will have RB scratch that off the required list for APO.

Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com <http://www.botts-inc.com/>
https://opensensorhub.org <https://opensensorhub.org/>
256-652-0165
