### ISSUE TITLE
OpenLayerView Initialization with OL Map Property

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-js#446]
OpenLayerView should allow initialization of the toolkit object even when a pre-created OL Map has been passed in.

Currently this view returns when map is passed as part of options:

```
        if (isDefined(options)) {
            //if the user passed in a map then use that one, don't make a new one
            if (options.map) {
                this.map = options.map;
                return;
            }

```
This prevents further initialization of elements necessary to render any elements on the map.  Furthermore, 

`       this.map = new Map({`

should only be called if

```
        if (!isDefined(this.map)) {

            this.map = new Map({
```

All other initialization proceeds correctly from this point.

**Comment by mdhsl** [comment]
Fixed #447
