### ISSUE TITLE
FFMpegView: exception while reseting

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#45]
The reset function will launch an exception due to missing function: _avcodec_flush_buffers

`Uncaught ReferenceError: _avcodec_flush_buffers is not defined
    at BaseClass.reset (osh.js:6895)`

We probably need to add that function into the ffmpeg compilation script.

This problem prevent changing time range using the range slider.

**Comment by alexrobin** [comment]
This method was there before but apparently the wrong version of the lib was used when copying to vendor-local
