### ISSUE TITLE
Synchronizer + batchMode

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#566]
The batchMode does not work with Synchronizer. Indeed, the algorithm skip DISCONNECTED datasource while iterating over the data. In batch mode, it is common to be disconnected before entering in this loop. So, the solution is to remove DISCONNECTED skip and to find a way to skip datasources which are disconnected AND which have no data anymore in algo (maybe using timestamp?)

**Comment by alexrobin** [comment]
Yes, I think we should skip a datasource only if it is disconnected AND there is no more data available from it.
