### ISSUE TITLE
OpenLayerView needs to allow for icon color specification

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-js#650]
The OpenLayerView allows for markers to be added with a given icon size and icon scale but not a color.

There should be a property to specify color as well:
https://github.com/opensensorhub/osh-js/blob/e3b2c10b69daede1582d0150dabb1a28a79f0aaa/source/core/ui/view/map/OpenLayerView.js#L315

**Comment by alexrobin** [comment]
I agree that it would be useful, but this would only apply to icons provided as black and white (or perhaps grayscale) I guess. Can OpenLayers recolor a PNG icon as well or does it work only with SVG?
