### ISSUE TITLE
DataSynchronizer support for dynamically adding and removing datasources

### ISSUE THREAD

**Issue by nickgaray** [opensensorhub/osh-js#691]
Use case:

- User has a number of 'visualizations' (composed of one or more data streams)
- User has ability to switch from real-time to playback
- User switches to playback mode (DataSyncrhonizer is created without any datasources added)
- User selects which visualizations to view/review (adding corresponding datasources to synchronizer)
- User connects data synchronizer

Extension to use case:
- User may elect to stop viewing a visualization (removing corresponding datasources from synchronizer)

Issue:
Adding a datasources to synchronizer before connecting but after creating synchronizer, the async setDataSynchronizer(dataSynchronizer) is not being invoked and when the request is made it is made without a time range such as this:
 
`ws://localhost:8282/sensorhub/api/datastreams/r5adq419u4h4c/observations?format=application/om%2Bjson`

**Comment by mdhsl** [comment]
Given your issue, the right way to add dataSource to the dataSynchronizer is to use the addDataSource function such like:


```js
const dataSynchronizer = new DataSynchronizer({
  replaySpeed: REPLAY_SPEED,
  timerResolution: 5,
  startTime: START_TIME,
  endTime: END_TIME,
  masterTimeRefreshRate: 25,
  dataSources: []
})

dataSynchronizer.addDataSource(platformLocationDataSource);
dataSynchronizer.addDataSource(platformOrientationDataSource);
dataSynchronizer.addDataSource(videoDataSource);

// start streaming
dataSynchronizer.connect();
```

full code:  https://github.com/opensensorhub/osh-js/blob/dev/showcase-dev/examples/datasources-synchronized-dynamic/datasources-synchronized-dynamic.js

Live example: https://opensensorhub.github.io/osh-js/dev/showcase-dev/datasources-synchronized-dynamic.html

**Comment by mdhsl** [comment]
What is not supported today is adding a dataSource after the dataSynchronizer is started.

**Comment by nickgaray** [comment]
The other operation is to remove a datasource, this is also currently not supported

`dataSyncrhonizer.removeDataSource(someDataSource)`

So, I agree with the adding but it would be great to also remove, in addition to the dataSyncrhonizer not reporting it is connected if it does not have any dataSources or if all its data sources are disconnected.

**Comment by mdhsl** [comment]
Example here: https://opensensorhub.github.io/osh-js/dev/showcase-dev/datasynchronizer-dynamic-add-remove.html
