### ISSUE TITLE
MISB demo creates extra images on the terrain on pause/resume

### ISSUE THREAD

**Issue by csdillard** [opensensorhub/osh-js#695]
To reproduce:

- Start the [`misb`](https://github.com/opensensorhub/osh-js/tree/dev/demos/misb) demo (with `npm run dev`), then visit the site in your browser.
- Click the button on the right to show the draped video image.
- Pause time with the button along the bottom of the window.
- Restart time with the same button.

Observe that there is now an extra image being drawn. The extra draped image also updates as the new video frames arrive.

Every time you pause and restart time, another extra image is added to the scene.

![Screenshot from 2022-12-02 14-24-54](https://user-images.githubusercontent.com/766641/205380058-f36e87f0-0122-464a-b6d5-90a537d7d74e.png)

**Comment by mdhsl** [comment]
I think this comes with my last changes #690, the layer should be reset correctly.
