### ISSUE TITLE
3-D model point markers can draw under draped images

### ISSUE THREAD

**Issue by csdillard** [opensensorhub/osh-js#716]
In a web app with a 3-D model point marker layer and a draped image layer, sometimes the 3-D model is incorrectly hidden by the draped image:

<img src="https://user-images.githubusercontent.com/766641/209001527-047c55a9-374d-4b80-83dc-7b12e66d9916.jpg" width="50%" height="50%" />

If you change the start time of playback (so that the video frames arrive sooner), the exact same code will correctly draw the 3-D model over the draped image:

<img src="https://user-images.githubusercontent.com/766641/209001704-b0dc4a38-2149-4448-807f-f9ec4febd7ec.jpg" width="50%" height="50%" />

**Comment by mdhsl** [comment]
I made some code to reproduce your problem and make sure that the marker is drawn first in the CesiumView but it doesn't seem to cause any z-index problem. The marker is always drawn on top even if the marker data comes before the draped image data.

Could you take the example [video-h264-draping](https://github.com/opensensorhub/osh-js/tree/dev/showcase/examples/video-h264-draping) and modify it to reproduce the problem?
