### ISSUE TITLE
Selected marker status not shown (on map) if no data has been received

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-js#85]
In the case of a fixed location, the selected status is taken into account only if the item has received data from the associated data sources. It should be possible to style the item with selected status even if no data has been received.

NOTE: I guess this is because updateMarker() is never called in this case

**Comment by mdhsl** [comment]
Some stuff have been done on this but this is now part of the global #89 issue. The whole selecting way has to be review
